FROM golang:1.25 AS builder

WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/daily-log-api ./cmd/api

FROM golang:1.25-alpine

WORKDIR /app
COPY --from=builder /out/daily-log-api /app/daily-log-api
EXPOSE 8080
ENTRYPOINT ["/app/daily-log-api"]
